---
name: CI

on:
  push:
    branches:
      - v1
    tags:
      - v*
  pull_request:
    branches:
      - v1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Run Tests
        run: |
          export PATH="$PATH:$PWD/exodus_core/dexdump/"
          python -m unittest discover -v -s exodus_core -p "test_*.py"
          python setup.py sdist
